export const GET_LOCATIONS_START = 'GET_LOCATIONS_START'
export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS'
export const GET_LOCATIONS_ERROR = 'GET_LOCATIONS_ERROR'

export const GET_ITINERARIES_START = 'GET_ITINERARIES_START'
export const GET_ITINERARIES_SUCCESS = 'GET_ITINERARIES_SUCCESS'
export const GET_ITINERARIES_ERROR = 'GET_ITINERARIES_ERROR'